before_script: 
  - "psql -c \"CREATE DATABASE testing_db;\" -U postgres"
  - "psql -c \"CREATE USER foo WITH PASSWORD 'bar';\" -U postgres"
env: 
  global: 
    - PGPORT=5432
language: node_js
node_js: 
  - node
services: 
  - postgresql
test: 
  adapter: postgresql
  database: testing_db
