language: node_js
node_js:
 - "node"
before_script: 
  - "psql -c \"CREATE DATABASE TESTING_DB;\" -U postgres"
  - "psql -c \"CREATE USER test WITH PASSWORD 'bar';\" -U postgres"
  - "cd server && npm i"
env: 
  global: 
  - PGPORT=5432
services: 
  - postgresql
test: 
  adapter: postgresql
  database: TESTING_DB
postgres://test:bar@localhost:5432/TESTING_DB